[files]
extend-exclude = [".git", "stl/**", "hershey-fonts/*"]

[default]
locale = "en"

[default.extend-words]
# allow list / custom corrections
CSG = "CSG"
csg = "csg"
cgs = "CSG"
CGS = "CSG"

iy = "iy"
toi = "toi"

# Abbreviation for homogeneous coordinates
hom = "hom"
# Acronym for Level-of-Detail
LOD = "LOD"
